#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "========================================"
echo "Cleaning RLVM build environment"
echo "========================================"

cd "$DIR"

# remove build directories
echo "Removing build directories..."
rm -rf build
rm -rf build-*

# remove toolchains generated by scripts
echo "Removing toolchain..."
rm -rf toolchain

# remove cmake cache files
echo "Removing CMake cache..."
find . -name "CMakeCache.txt" -delete
find . -name "CMakeFiles" -type d -exec rm -rf {} +

# remove intermediate libraries (but keep NDK libraries)
echo "Removing compiled libraries..."
find . -type f \( -name "*.a" -o -name "*.so" -o -name "*.o" \) ! -path "./toolchain/ndk/*" -delete

# remove compiled JNI libraries from app module (forces rebuild on next gradle build)
echo "Removing stale JNI libraries from app/src/main/jniLibs/..."
rm -rf "$DIR/../app/src/main/jniLibs/"

echo ""
echo "Clean complete."
echo "You can now run:"
echo ""
echo "   ./build.sh --arch arm64 2>&1 | tee build.log"
echo ""